version: '3'
services:
  pokedex_db_local:
    container_name: pokedex_db_local
    image: library/postgres
    ports:
      - 5432:3306
    environment:
      POSTGRES_DB: pokedex_db
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: devsecret