#server:
#  servlet:
#    context-path: /api
#  port: 9081

spring:
  data:
    web:
      pageable:
        default-page-size: 15
        one-indexed-parameters: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/pokemonBE"
#    url: "jdbc:postgresql://localhost:5432/pokedex_db"

    username: "davidvinson"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

#==== springdoc openapi ======#
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger


##==== springdoc openapi ======#
#  springdoc.api-docs.path=/docs
#  springdoc.swagger-ui.path=/swagger

